### ISSUE TITLE
dark mode for dino game (feature)

### ISSUE THREAD

**Issue by mehulsatardekar** [tomayac/chrome-dino-gamepad#1]
hi @tomayac ..i was  wondering  what if dino game gets a dark theme feature i think it would look nice as well as it could save our eyes from digital stain whos playing this game for long Time. if you want to add dark theme mode i can make a PR. 

preview
![Screenshot from 2020-10-25 19-50-43](https://user-images.githubusercontent.com/36101139/97110048-06b51600-16fd-11eb-8f6c-9067b78e4a86.png)

**Comment by tomayac** [comment]
If it's not a lot of code I'm happy to accept a PR. Thank you!
